# Generated by Django 5.2 on 2025-04-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='Instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Twitter',
            new_name='twitter',
        ),
    ]
